# Generated by Django 2.2.19 on 2021-06-25 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='Oferta',
        ),
    ]
