# Generated by Django 2.2.17 on 2021-03-02 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_news', models.CharField(max_length=70)),
                ('description', models.TextField(verbose_name='Новости')),
                ('image_news', models.ImageField(upload_to='img/news')),
                ('published', models.DateTimeField(verbose_name='Дата публикации')),
            ],
        ),
    ]
