# Generated by Django 2.2.19 on 2022-02-01 14:41

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20220201_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='description_2',
            field=django_ckeditor_5.fields.CKEditor5Field(default=1, verbose_name='Текст статьи'),
            preserve_default=False,
        ),
    ]
