# Generated by Django 2.2.19 on 2022-02-02 15:27

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_news_description_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='description_2',
        ),
        migrations.AlterField(
            model_name='news',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Текст статьи'),
        ),
    ]
