# Generated by Django 2.2.19 on 2021-04-07 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('telega_link', models.CharField(max_length=120)),
                ('facebook_link', models.CharField(max_length=120)),
                ('instagram_link', models.CharField(max_length=120)),
            ],
        ),
    ]
